<?xml version="1.0" encoding="UTF-8"?>
<messages cleanup="false" >

  <Message id="{{addon_prefix}}00001E" group="{{addon_prefix_lower}}artist" key="DateCannotBeFuture" prefix="1">
    <Display method="MSGBOX">
      <Option>MSG_BTNOK</Option>
    </Display>
    <MsgText>Birth date cannot be in future.</MsgText> 
  </Message>
  
  <Message id="{{addon_prefix}}00002E" group="{{addon_prefix_lower}}artist" key="CannotDeleteArtistWithMusic" prefix="1">
    <Display method="MSGBOX">
      <Option>MSG_BTNOK</Option>
    </Display>
    <MsgText>This artist {0} cannot be deleted because it is associated with some musics.</MsgText> 
  </Message>
  
  <Message id="{{addon_prefix}}00003I" group="{{addon_prefix_lower}}artist" key="NoMusicToSelect" prefix="1">
    <Display method="MSGBOX">
      <Option>MSG_BTNOK</Option>
    </Display>
    <MsgText>All the musics are already associated with artists. No selection available.</MsgText> 
  </Message>

</messages>